### ISSUE TITLE
Week 1 Tangibles

### ISSUE THREAD

**Issue by AadyaDaita** [AadyaDaita/apcsa_indiv_repo_tri1#3]
## [Aadya's Fastpage](https://aadyadaita.github.io/apcsa_indiv_repo_tri1/)   2.7+

- [x] Seeing that you understand how to use Code.org and that you used it to complement your learning on primitives.  Up to Lesson 5 in the OOP assignment. - done
![image](https://user-images.githubusercontent.com/89221238/187241701-c7a0eb5a-6896-4965-9a70-f2e11f35762f.png)

- [x] Productive Blogging
  - [x]   Create a Jupyter Notebook(s) using IJava kernel and that you could use it to capture key learning on Primitives.  - also finished the hacks on the primitives: [here are the notes and the code that demonstrates it](https://aadyadaita.github.io/apcsa_indiv_repo_tri1/notes/)
  - [x]   Create a Jupyter Notebook using Bash and that you could use it to show that you have all the key tools installed.   This should also be a Blog for your own personal memory. -  finished that hacks about checking whether the tools have been installed through shell script. Also took notes on how to use shell script [demonstrated here](https://aadyadaita.github.io/apcsa_indiv_repo_tri1/2022/08/25/bash_kernel.html)
  - [x]   Each student captures information  in Fastpages thinking ... how they are going to capture information that will grow to 10 college board units ... how they will recognize something as PBL vs College Board. - created a [notes page](https://aadyadaita.github.io/apcsa_indiv_repo_tri1/notes/) that distinguishes the different notes for college board topics and pbl features
  - [x] [Personalised fastpage](https://aadyadaita.github.io/apcsa_indiv_repo_tri1/random/) with images and more. also added content about interests, and topics outside CS

**Comment by shreya-ahujaa** [comment]
## Peer Review Grade for Aadya Daita: 2.7+

- [x] Seeing that you understand how to use Code.org and that you used it to complement your learning on primitives.  Up to Lesson 5 in the OOP assignment
     - [ ]  shown in screenshot
- [x] Productive Blogging 
    - [ ] shown through the other examples
- [x] Create a Jupyter Notebook(s) using IJava kernel and that you could use it to capture key learning on Primitives
    - [ ]  she has the IJava Kernel and used it to learn more about primitives
- [x] Create a Jupyter Notebook using Bash and that you could use it to show that you have all the key tools installed.   This should also be a Blog for your own personal memory.
     - [ ] Bash and Checks page to check for installations
- [x] Each student captures information  in Fastpages thinking ... how they are going to capture information that will grow to 10 college board units ... how they will recognize something as PBL vs College Board.
     - [ ] table with one column for collegeboard and other for PBL
